services:
  - type: web
    name: shop-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python shop_bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: TURSO_DATABASE_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
      - key: CRYPTOPAY_TOKEN
        sync: false
